<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.10">
  <POU Name="F_LminToEng" Id="{575677ff-2a4b-4d5e-af39-dad63e3f7450}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION F_LminToEng : LREAL
VAR_INPUT
	fLminFlow : LREAL;
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[F_LminToEng := fLminFlow / 60000;
]]></ST>
    </Implementation>
    <LineIds Name="F_LminToEng">
      <LineId Id="7" Count="0" />
      <LineId Id="14" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>